### ISSUE TITLE
Specialization switch error

### ISSUE THREAD

**Issue by Cudyhouse** [tukui-org/ElvUI#1470]
### Troubleshooting Steps

![Image](https://github.com/user-attachments/assets/5c2b3fe8-9447-4eec-a54c-7ca4a4466fc7)

### Describe the expected behavior and what actually happened?

just trying to use the switch spe datatext

### Reproducing the issue.

just trying to use the switch spe datatext

### Lua Errors

```shell
Message: ...dOns/ElvUI/Mainline/Modules/DataTexts/SpecSwitch.lua:87: attempt to call upvalue 'SetSpecialization' (a nil value)
Time: Wed Feb 26 12:07:02 2025
Count: 2
Stack:
[Interface/AddOns/ElvUI/Mainline/Modules/DataTexts/SpecSwitch.lua]:87: in function 'func'
[Interface/AddOns/ElvUI/Core/General/API.lua]:1164: in function <Interface/AddOns/ElvUI/Core/General/API.lua:1164>
[tail call]: ?
[C]: in function 'securecallfunction'
[Interface/AddOns/Blizzard_Menu/Menu.lua]:884: in function 'Pick'
[Interface/AddOns/Blizzard_Menu/MenuTemplates.lua]:74: in function <Interface/AddOns/Blizzard_Menu/MenuTemplates.lua:68>

Locals:
_ = nil
arg1 = 1
(*temporary) = nil
(*temporary) = 1
(*temporary) = "attempt to call upvalue 'SetSpecialization' (a nil value)"
SetSpecialization = nil
DT = <table> {
 modules = <table> {
 }
 DataTextList = <table> {
 }
 QuickList = <table> {
 }
 tooltip = DataTextTooltip {
 }
 PanelPool = <table> {
 }
 defaultModuleState = true
 hooks = <table> {
 }
 UnitEvents = <table> {
 }
 LoadedInfo = <table> {
 }
 db = <table> {
 }
 enabledState = true
 RegisteredPanels = <table> {
 }
 SelectedDatatext = LeftChatDataPanel_DataText1 {
 }
 ClassTalentsID = 52074871
 baseName = "ElvUI"
 CurrencyList = <table> {
 }
 SystemInfo = <table> {
 }
 ForceHideBGStats = false
 defaultModuleLibraries = <table> {
 }
 FontStrings = <table> {
 }
 Initialized = true
 SPECIALIZATION_CACHE = <table> {
 }
 AssignedDatatexts = <table> {
 }
 name = "ElvUI_DataTexts"
 orderedModules = <table> {
 }
 RegisteredDataTexts = <table> {
 }
 clientFullName = <table> {
 }
 moduleName = "DataTexts"
}
```

### Verification Steps

- [x] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [x] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [x] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
Thanks for the report.  

This is already fixed in dev which you can manually download and install or wait until next release - no eta 

https://api.tukui.org/v1/download/dev/elvui/main

**Comment by Cudyhouse** [comment]
Thanks for your answer.
I tried to install your version but ... this is not working for me.
I think i will wait for the release instead :)
but thanks :)

**Comment by raptormama** [comment]
Same issue at first, with the same error. The dev version does not fix. Version `13.85-4-gea56326` has the same outward issue but logs a slightly different error:

```1x ...dOns/ElvUI/Mainline/Modules/DataTexts/SpecSwitch.lua:87: attempt to call upvalue 'SetSpecialization' (a nil value)
[ElvUI/Mainline/Modules/DataTexts/SpecSwitch.lua]:87: in function 'func'
[ElvUI/Core/General/API.lua]:1164: in function <ElvUI/Core/General/API.lua:1164>
[tail call]: ?
[C]: in function 'securecallfunction'
[Blizzard_Menu/Menu.lua]:884: in function 'Pick'
[Blizzard_Menu/MenuTemplates.lua]:74: in function <Blizzard_Menu/MenuTemplates.lua:68>

**Comment by kodewdle** [comment]
this wasn't fixed yet, bot mixed up issues on accident.  i have this pinned to look at soon.

**Comment by kodewdle** [comment]
should be fixed by: https://github.com/tukui-org/ElvUI/commit/809fc6a04d8e52ff93b59a470e6302e5e8be34f1

**Comment by raptormama** [comment]
Manually changed the line and can confirm that it does fix it. Thank you!
