### ISSUE TITLE
Some minimap addon buttons revert to inside the map near middle upon zoning/logging/reloading ui

### ISSUE THREAD

**Issue by Stevespim** [tukui-org/ElvUI#1487]
### Troubleshooting Steps

Some of my addon buttons move from the outside of the minimap to the inside, near the middle, in a circle format, almost like they are trying to stick to a smaller round minimap

![Image](https://github.com/user-attachments/assets/074049cd-5b91-4cbd-a1b9-dd56e0e028df)

### Describe the expected behavior and what actually happened?

Obviously this error doesn't occur with no addons installed, as it is the addon buttons that normally surround the minimap that are seeing errors.. In Elvui 13.85 everything was fine and all the addon buttons stayed on the edge of the minimap. In 13.86, some of my addon buttons cluster over each other near the middle of the minimap. If I move them to the outside of the map where they used to be in the previous ELlvui version, upon logging, zoning or reloading the UI, they all snap back to the middle of the minimap again, overlapping each other. Again, these addon buttons were fine in 13.85, which makes me think it is a change in Elvui, rather than the addons themselves, all of which are on the latest versions, some of which have been updated by the developers in the last few days. If it had been one or two addons, I would agree that they are probably at fault, however being that there are so many of them, it lends me to think that the error lies in Elvui.

### Reproducing the issue.

Basically for me it is load the game and the addon buttons are in the wrong place. If I move them to the correct places on the outside of the minimap then reload the UI, they all snap back to the middle of the minimap again.

### Lua Errors

```shell
No LUA errors
```

### Verification Steps

- [x] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [x] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [x] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
This has happened to people randomly in the past.  

There was a change to the ElvUI minimap, so not sure if that changed it.   or if ElvUI can influence where the icons go. 
If ElvUI can't, or in the meantime, you can use a Square Minimap Buttons addon - like https://www.curseforge.com/wow/addons/projectazilroka
*Note - it has quite a few features - you may want to look at what it provides - all of them can be enabled/disabled to suit.

**Comment by 1Botanica1** [comment]
This is fixed in dev which you can manually download and install or wait until next release - no eta

https://api.tukui.org/v1/download/dev/elvui/main

**Comment by Stevespim** [comment]
I appreciate that. Thank you.

**Comment by Stevespim** [comment]
The dev version doesn't fix the issue, so i'll check out Project Azilroka. Thanks for the heads up.

**Comment by 1Botanica1** [comment]
> The dev version doesn't fix the issue, so i'll check out Project Azilroka. Thanks for the heads up.

Can you please type 
`/estatus` and upload a full UI screenshot showing the issue and the status panel.

**Comment by Stevespim** [comment]
![Image](https://github.com/user-attachments/assets/2a1baf07-1a88-4c53-b184-a59390438525)

**Comment by Stevespim** [comment]
![Image](https://github.com/user-attachments/assets/49a3fddc-f9cc-4543-8b91-9d2643cd8ce5)

**Comment by kodewdle** [comment]
try dev again and post estatus again, please and thank you 🌼
