### ISSUE TITLE
[Retail Bug Report] <Incorrect tooltip border color>

### ISSUE THREAD

**Issue by awedy01** [tukui-org/ElvUI#37]
### What is the issue you are having?

It uses the wrong border color for items, for example:
Korthian Caretaker's Mitts (cloth hands) (epic item) is green border colored
Phantasmic Infuser (epic item) is grey border colored

### What is the expected behavior?

To show the correct quality color, epic items > epic border color

### What actually happened?

As said above: Showing item tooltip with wrong border color when Item Quality (at Tooltip options) is checked on

Some extra info:
I use tooltip at Mouse anchor
I have latest version of ElvUI
I also tested latest DEV version of ElvUI

### Errors

```shell
I've got 2 lua errors
Message: ...erface\AddOns\ElvUI\Core\Modules\Tooltip\Tooltip.lua:674: attempt to call method 'SetBackdropBorderColor' (a nil value)
Time: Thu Nov  4 13:13:10 2021
Count: 27
Stack: ...erface\AddOns\ElvUI\Core\Modules\Tooltip\Tooltip.lua:674: attempt to call method 'SetBackdropBorderColor' (a nil value)
[string "=[C]"]: in function `SetBackdropBorderColor'
[string "@Interface\AddOns\ElvUI\Core\Modules\Tooltip\Tooltip.lua"]:674: in function <...erface\AddOns\ElvUI\Core\Modules\Tooltip\Tooltip.lua:654>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@Interface\FrameXML\ContainerFrame.lua"]:1372: in function `UpdateTooltip'
[string "@Interface\FrameXML\GameTooltip.lua"]:477: in function <Interface\FrameXML\GameTooltip.lua:464>

Locals: 





Message: ...erface\AddOns\ElvUI\Core\Modules\Tooltip\Tooltip.lua:674: attempt to call method 'SetBackdropBorderColor' (a nil value)
Time: Thu Nov  4 13:13:07 2021
Count: 10
Stack: ...erface\AddOns\ElvUI\Core\Modules\Tooltip\Tooltip.lua:674: attempt to call method 'SetBackdropBorderColor' (a nil value)
[string "=[C]"]: in function `SetBackdropBorderColor'
[string "@Interface\AddOns\ElvUI\Core\Modules\Tooltip\Tooltip.lua"]:674: in function <...erface\AddOns\ElvUI\Core\Modules\Tooltip\Tooltip.lua:654>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@Interface\FrameXML\ContainerFrame.lua"]:1372: in function `ContainerFrameItemButton_OnUpdate'
[string "@Interface\FrameXML\ContainerFrame.lua"]:1419: in function `ContainerFrameItemButton_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals:
```

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog) and done the [Troubelshooting Steps](https://www.tukui.org).

**Comment by Merathilis** [comment]
Okay, first off all. This is the Retail Ticket Tracker not for tbc :P

**Comment by kodewdle** [comment]
This issue was fixed already. Perhaps you updated to the wrong folder?


Here is the code that fixed the issue (specifically .NineSlice was missing):
```lua
if tt.NineSlice then
	tt.NineSlice:SetBackdropBorderColor(GetItemQualityColor(quality))
else
	tt:SetBackdropBorderColor(GetItemQualityColor(quality))
end
```

**Comment by awedy01** [comment]
Yeah so using the latest dev version from !dev on discord, it is not fixed yet.
I also checked with /edebug on which causes no item border to be colored
I get Lua Error with it about tooltip

Lua error 1
Message: ...erface\AddOns\ElvUI\Core\Modules\Tooltip\Tooltip.lua:674: attempt to call method 'SetBackdropBorderColor' (a nil value)
Time: Fri Nov  5 09:25:29 2021
Count: 39
Stack: ...erface\AddOns\ElvUI\Core\Modules\Tooltip\Tooltip.lua:674: attempt to call method 'SetBackdropBorderColor' (a nil value)
[string "=[C]"]: in function `SetBackdropBorderColor'
[string "@Interface\AddOns\ElvUI\Core\Modules\Tooltip\Tooltip.lua"]:674: in function <...erface\AddOns\ElvUI\Core\Modules\Tooltip\Tooltip.lua:654>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@Interface\FrameXML\ContainerFrame.lua"]:1372: in function `ContainerFrameItemButton_OnUpdate'
[string "@Interface\FrameXML\ContainerFrame.lua"]:1419: in function `ContainerFrameItemButton_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals: 



Lua error 2
Message: ...erface\AddOns\ElvUI\Core\Modules\Tooltip\Tooltip.lua:674: attempt to call method 'SetBackdropBorderColor' (a nil value)
Time: Fri Nov  5 09:25:29 2021
Count: 65
Stack: ...erface\AddOns\ElvUI\Core\Modules\Tooltip\Tooltip.lua:674: attempt to call method 'SetBackdropBorderColor' (a nil value)
[string "=[C]"]: in function `SetBackdropBorderColor'
[string "@Interface\AddOns\ElvUI\Core\Modules\Tooltip\Tooltip.lua"]:674: in function <...erface\AddOns\ElvUI\Core\Modules\Tooltip\Tooltip.lua:654>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@Interface\FrameXML\ContainerFrame.lua"]:1372: in function `UpdateTooltip'
[string "@Interface\FrameXML\GameTooltip.lua"]:477: in function <Interface\FrameXML\GameTooltip.lua:464>

Locals: 



Lua error 3
Message: ...erface\AddOns\ElvUI\Core\Modules\Tooltip\Tooltip.lua:674: attempt to call method 'SetBackdropBorderColor' (a nil value)
Time: Fri Nov  5 09:25:18 2021
Count: 1
Stack: ...erface\AddOns\ElvUI\Core\Modules\Tooltip\Tooltip.lua:674: attempt to call method 'SetBackdropBorderColor' (a nil value)
[string "=[C]"]: in function `SetBackdropBorderColor'
[string "@Interface\AddOns\ElvUI\Core\Modules\Tooltip\Tooltip.lua"]:674: in function <...erface\AddOns\ElvUI\Core\Modules\Tooltip\Tooltip.lua:654>
[string "=(tail call)"]: ?
[string "=[C]"]: ?

Locals:
