### ISSUE TITLE
[Retail Bug Report] Cannot use blizzard action bars after disabling ElvUI action bars (sometimes)

### ISSUE THREAD

**Issue by zealain** [tukui-org/ElvUI#660]
### What is the issue you are having?

Sometimes pressing the keybind for an ability does not work. The ability flashes up on the action bar and an error sound plays, but the ability is not cast. I haven't found a reliable way to reproduce it yet, but I think entering the Blizzard UI Edit Mode can trigger it. I have ElvUI installed, but the action bar module disabled. The reason I believe this to be an ElvUI bug, is that I get a LUA error from ElvUI related to action bars right when it happens, despite having ElvUI action bars disabled. As I can't reliably reproduce it, it's hard to say whether it _really_ doesn't happen without ElvUI active though. For some reason, clicking the spell on the action bar with the mouse still works, though.

### What is the expected behavior?

Pressing the keybind for an action bar button activates the ability on that action bar slot.

### What actually happened?

An error sounds plays and the ability is not activated.

### Errors

```shell
2x [ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: in function `UseAction'
[string "@FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@FrameXML/SecureTemplates.lua"]:690: in function <FrameXML/SecureTemplates.lua:672>
[string "@FrameXML/SecureTemplates.lua"]:704: in function <FrameXML/SecureTemplates.lua:697>
[string "@FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@FrameXML/ActionButton.lua"]:109: in function `TryUseActionButton'
[string "@FrameXML/ActionButton.lua"]:144: in function `ActionButtonDown'
[string "ACTIONBUTTON1"]:2: in function <[string "ACTIONBUTTON1"]:1>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
should be fixed in 13.08; you didn't report version so closing this assuming you are just out-of-date

**Comment by zealain** [comment]
@kodewdle Ah yes, I did forget to mention the version, sorry. Unfortunately I am not out-of-date and the issue still happens in 13.08. I managed to reproduce it pretty reliably by entering/exiting edit mode, followed by mounting a dragonriding mount.
