### ISSUE TITLE
[Retail Bug Report] Loot Roll Lua error in raids

### ISSUE THREAD

**Issue by VaporAPX** [tukui-org/ElvUI#737]
### What is the issue you are having?

This error fires every time a boss dies and the loot rolls screen pops up. Causes the loot rolls to stay up on the screen permanently until a UI reload.

### What is the expected behavior?

No error, and the loot roll frame should leave the screen once the options are all selected and loot is awarded.

### What actually happened?

Error, and loot roll window never leaves the screen.

### Errors

```shell
43x ElvUI/Core/Modules/Misc/LootRoll.lua:265: attempt to index local 'f' (a nil value)
[string "@ElvUI/Core/Modules/Misc/LootRoll.lua"]:265: in function <ElvUI/Core/Modules/Misc/LootRoll.lua:254>
[string "=[C]"]: in function `?'
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:363
 RaidMarkButton_OnLeave = <function> defined @ElvUI/Core/Modules/Misc/RaidMarker.lua:70
 ClearPageInfo = <function> defined @ElvUI/Core/Modules/Misc/InfoItemLevel.lua:82
 EnableModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 CancelTimer = <function> defined @Ace3/AceTimer-3.0/AceTimer-3.0.lua:147
 IterateEmbeds = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:438
 UpdateAverageString = <function> defined =[C]:-1
 SecureHookScript = <function> defined @Ace3/AceHook-3.0/AceHook-3.0.lua:409
 MERCHANT_SHOW = <function> defined @ElvUI/Core/Modules/Misc/Misc.lua:204
 LOOT_HISTORY_ROLL_COMPLETE = <function> defined @ElvUI/Core/Modules/Misc/LootRoll.lua:376
 ZoneTextToggle = <function> defined @ElvUI/Core/Modules/Misc/Misc.lua:89
 RawHookScript = <function> defined @Ace3/AceHook-3.0/AceHook-3.0.lua:394
 DisbandRaidGroup = <function> defined @ElvUI/Core/Modules/Misc/Misc.lua:218
 SetDefaultModulePrototype = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:405
 QUEST_COMPLETE = <function> defined @ElvUI/Core/Modules/Misc/Misc.lua:285
 defaultModuleState = true
 BossBanner_ConfigureLootFrame = <function> defined @ElvUI/Core/Modules/Misc/Misc.lua:319
 IsEnabled = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:447
 ScheduleTimer = <function> defined @Ace3/AceTimer-3.0/AceTimer-3.0.lua:94
 DisableModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:346
 ErrorFrameToggle = <function> defined @ElvUI/Core/Modules/Misc/Misc.lua:79
 ADDON_LOADED = <function> defined @ElvUI/Core/Modules/Misc/Misc.lua:277
 RegisterMessage = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterMessage = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 LOOT_HISTORY_ROLL_CHANGED = <function> defined @ElvUI/Core/Modules/Misc/LootRoll.lua:349
 hooks = <table> {
 }
 UI_ERROR_MESSAGE = <function> defined @ElvUI/Core/Modules/Misc/Misc.lua:189
 ToggleItemLevelInfo = <function> defined =[C]:-1
 SetEnabledState = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @Ace3/AceHook-3.0/AceHook-3.0.lua:273
 enabledState = true
 COMBAT_LOG_EVENT_UNFILTERED = <function> defined @ElvUI/Core/Modules/Misc/Misc.lua:99
 RegisterEvent = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UpdateLootRollAnchors = <function> defined @ElvUI/Core/Modules/Misc/LootRoll.lua:382
 BubbleFrame = Frame {
 }
 RaidMarkFrame = Frame {
 }
 IterateModules = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:433
 AddChatBubbleName = <function> defined @ElvUI/Core/Modules/Misc/ChatBubbles.lua:72
 RawHook = <function> defined @Ace3/AceHook-3.0/AceHook-3.0.lua:312
 TryGearAgain = <function> defined @ElvUI/Core/Modules/Misc/InfoItemLevel.lua:225
 baseName = "ElvUI"
 UpdateInspectPageFonts = <function> defined =[C]:-1
 SetupInspectPageInfo = <function> defined @ElvUI/Core/Modules/Misc/InfoItemLevel.lua:317
 RaidMarkButton_OnEnter = <function> defined @ElvUI/Core/Modules/Misc/RaidMarker.lua:64
 CreateSlotStrings = <function> defined =[C]:-1
 LootFrame_GetFrame = <function> defined @ElvUI/Core/Modules/Misc/LootRoll.lua:231
 LoadLootRoll = <function> defined @ElvUI/Core/Modules/Misc/LootRoll.lua:473
 RESURRECT_REQUEST = <function> defined @ElvUI/Core/Modules/Misc/Misc.lua:271
 New
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
This has been addressed in the development build

**Comment by VaporAPX** [comment]
Excellent, thank you!

**Comment by VaporAPX** [comment]
This no longer fires an error in the current release build, but the roll frame still remains on your screen and does not clear without a reload of the UI. So not fully fixed.

**Comment by kodewdle** [comment]
try on 13.17, tried something else :)

**Comment by swetty314** [comment]
I still have the issue on 13.17 where the loot roll frame remains until a UI reload.

**Comment by VaporAPX** [comment]
I tested it last night, worked fine for me with current version. No issue.

**Comment by kodewdle** [comment]
https://github.com/evil-morfar/RCLootCouncil2/commit/dd79fd4de1cafd5038cb88d2fa0ab9aaf158c55a related
