### ISSUE TITLE
[Retail Bug Report] Clicking on gold Datatext does not open bags anymore

### ISSUE THREAD

**Issue by omgshooz** [tukui-org/ElvUI#798]
### What is the issue you are having?

Clicking on my gold in the Datatext bar beneath the chat frame no longer opens my bags after updating to 13.23

### What is the expected behavior?

Clicking on the gold datatext used to open up my bags

### What actually happened?

Clicking on the gold datatext now does absolutely nothing. 

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
This is fixed in dev.

**Comment by omgshooz** [comment]
I'm not sure what you mean by that? I have the most up to date version and it's still not working

**Comment by Azilroka** [comment]
You have the most updated release.. not the development version that you have to get from github or from the !dev command on discord
