### ISSUE TITLE
[Wrath Bug Report] Totembar setbackdropbordercolor

### ISSUE THREAD

**Issue by Larsy93** [tukui-org/ElvUI#861]
### What is the issue you are having?

80x ...eElvUI/Wrath/Modules/ActionBars/TotemBar.lua:60: attempt to call method 'SetBackdropBorderColor' (a nil value)
[string "@ElvUI/Wrath/Modules/ActionBars/TotemBar.lua"]:60: in function <...eElvUI/Wrath/Modules/ActionBars/TotemBar.lua:57>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `MultiCastSlotButton_Update'
[string "@FrameXML/MultiCastActionBarFrame.lua"]:316: in function `MultiCastActionBarFrame_Update'
[string "@FrameXML/MultiCastActionBarFrame.lua"]:225: in function <FrameXML/MultiCastActionBarFrame.lua:223>

Locals:
self = <table> {
 SetAuraCooldowns = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:1535
 SetupFlyoutButton = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:1440
 modules = <table> {
 }
 ApplyTextOption = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:569
 ConfigureProfessionQuality = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:727
 ShownMicroButtons = <function> defined @ElvUI/Core/Modules/ActionBars/MicroBar.lua:244
 FadeBarBlings = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:777
 ActivateBindMode = <function> defined @ElvUI/Core/Modules/ActionBars/Bind.lua:34
 Button_OnEnter = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:810
 SetDefaultModulePrototype = <function> defined @Questie/Libs/AceAddon-3.0/AceAddon-3.0.lua:405
 SkinMultiCastButton = <function> defined @ElvUI/Wrath/Modules/ActionBars/TotemBar.lua:65
 IsEnabled = <function> defined @Questie/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 SettingsDisplayCategory = <function> defined @ElvUI/Core/Modules/ActionBars/Bind.lua:298
 UpdatePetBindings = <function> defined @ElvUI/Core/Modules/ActionBars/PetBar.lua:198
 UpdateMicroBarTextures = <function> defined @ElvUI/Core/Modules/ActionBars/MicroBar.lua:322
 CreateBarPet = <function> defined @ElvUI/Core/Modules/ActionBars/PetBar.lua:239
 RegisterMessage = <function> defined @Questie/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:85
 UnregisterMessage = <function> defined @Questie/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:148
 LAB_ButtonCreated = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:1601
 hooks = <table> {
 }
 DisplayBindsTooltip = <function> defined @ElvUI/Core/Modules/ActionBars/Bind.lua:118
 db = <table> {
 }
 LAB_FlyoutUpdate = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:1566
 Bar_OnLeave = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:797
 SpellBookTooltipOnUpdate = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:904
 UPDATE_SHAPESHIFT_COOLDOWN = <function> defined @ElvUI/Core/Modules/ActionBars/StanceBar.lua:25
 FixKeybindColor = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:1331
 LAB_FlyoutCreated = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:1578
 BlizzardOptionsPanel_OnEvent = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:837
 ColorSwipeTexture = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:753
 NewModule = <function> defined @Questie/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 PositionAndSizeBarShapeShift = <function> defined @ElvUI/Core/Modules/ActionBars/StanceBar.lua:91
 UpdateFlyoutButtons = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:1418
 UpdateStanceBindings = <function> defined @ElvUI/Core/Modules/ActionBars/StanceBar.lua:225
 StyleFlyout = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:1457
 Button_OnLeave = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:823
 Initialized = true
 UpdateTotemBindings = <function> defined @ElvUI/Wrath/Modules/ActionBars/TotemBar.lua:240
 ButtonEventsRegisterFrame = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:982
 UpdateAuraCooldown = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:1507
 GetName = <function> defined @Questie/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
 FadeBlingTexture = <func

### What is the expected behavior?

no error

### What actually happened?

logging in

### Errors

```shell
80x ...eElvUI/Wrath/Modules/ActionBars/TotemBar.lua:60: attempt to call method 'SetBackdropBorderColor' (a nil value)
[string "@ElvUI/Wrath/Modules/ActionBars/TotemBar.lua"]:60: in function <...eElvUI/Wrath/Modules/ActionBars/TotemBar.lua:57>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `MultiCastSlotButton_Update'
[string "@FrameXML/MultiCastActionBarFrame.lua"]:316: in function `MultiCastActionBarFrame_Update'
[string "@FrameXML/MultiCastActionBarFrame.lua"]:225: in function <FrameXML/MultiCastActionBarFrame.lua:223>

Locals:
self = <table> {
 SetAuraCooldowns = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:1535
 SetupFlyoutButton = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:1440
 modules = <table> {
 }
 ApplyTextOption = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:569
 ConfigureProfessionQuality = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:727
 ShownMicroButtons = <function> defined @ElvUI/Core/Modules/ActionBars/MicroBar.lua:244
 FadeBarBlings = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:777
 ActivateBindMode = <function> defined @ElvUI/Core/Modules/ActionBars/Bind.lua:34
 Button_OnEnter = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:810
 SetDefaultModulePrototype = <function> defined @Questie/Libs/AceAddon-3.0/AceAddon-3.0.lua:405
 SkinMultiCastButton = <function> defined @ElvUI/Wrath/Modules/ActionBars/TotemBar.lua:65
 IsEnabled = <function> defined @Questie/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 SettingsDisplayCategory = <function> defined @ElvUI/Core/Modules/ActionBars/Bind.lua:298
 UpdatePetBindings = <function> defined @ElvUI/Core/Modules/ActionBars/PetBar.lua:198
 UpdateMicroBarTextures = <function> defined @ElvUI/Core/Modules/ActionBars/MicroBar.lua:322
 CreateBarPet = <function> defined @ElvUI/Core/Modules/ActionBars/PetBar.lua:239
 RegisterMessage = <function> defined @Questie/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:85
 UnregisterMessage = <function> defined @Questie/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:148
 LAB_ButtonCreated = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:1601
 hooks = <table> {
 }
 DisplayBindsTooltip = <function> defined @ElvUI/Core/Modules/ActionBars/Bind.lua:118
 db = <table> {
 }
 LAB_FlyoutUpdate = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:1566
 Bar_OnLeave = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:797
 SpellBookTooltipOnUpdate = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:904
 UPDATE_SHAPESHIFT_COOLDOWN = <function> defined @ElvUI/Core/Modules/ActionBars/StanceBar.lua:25
 FixKeybindColor = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:1331
 LAB_FlyoutCreated = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:1578
 BlizzardOptionsPanel_OnEvent = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:837
 ColorSwipeTexture = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:753
 NewModule = <function> defined @Questie/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 PositionAndSizeBarShapeShift = <function> defined @ElvUI/Core/Modules/ActionBars/StanceBar.lua:91
 UpdateFlyoutButtons = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:1418
 UpdateStanceBindings = <function> defined @ElvUI/Core/Modules/ActionBars/StanceBar.lua:225
 StyleFlyout = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:1457
 Button_OnLeave = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:823
 Initialized = true
 UpdateTotemBindings = <function> defined @ElvUI/Wrath/Modules/ActionBars/TotemBar.lua:240
 ButtonEventsRegisterFrame = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:982
 UpdateAuraCooldown = <function> defined @ElvUI/Core/Modules/ActionBars/ActionBars.lua:1507
 GetName = <function> defined @Questie/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
 FadeBlingTexture = <func
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
Are you on dev? /estatus

**Comment by Larsy93** [comment]
I am on dev yes.

**Comment by Azilroka** [comment]
Make sure to pull the latest commit. That should fix that.

**Comment by Larsy93** [comment]
Hi, still have this issue, it happens when masque is enabled, it was not a problem with previouse ElvUI releases.
